// src/app/api/admin/import/template/route.ts
import { NextResponse } from 'next/server';

export async function GET() {
  const headers = [
    'name',
    'brand',
    'category',
    'model',
    'sku',
    'tonnageOrCapacity',
    'starRating',
    'coolingType',
    'refrigerant',
    'iseer',
    'powerConsumption',
    'coilMaterial',
    'shortSummary',
    'description',
    'suitableFor',
    'features',
    'specs',
    'images',
    'warranty',
    'availability',
    'isDemo',
  ].join(',');

  const sampleRows = [
    [
      '"Daikin 1.5 Ton 5-Star Inverter Split AC"',
      '"Daikin"',
      '"split-ac"',
      '"FTKM50 Series"',
      '"DAIKIN-FTKM50-DEMO"',
      '"1.5 Ton"',
      '"5"',
      '"Inverter Split Cooling"',
      '"R-32"',
      '"5.20"',
      '"785 kWh/year"',
      '"100% Grooved Copper"',
      '"High-efficiency inverter split AC featuring rapid cooling, PM 2.5 air filtration, and durable copper coils."',
      '"Daikin 1.5 Ton 5-Star Inverter Split AC delivers reliable climate control engineered for Andhra Pradesh heat."',
      '"Medium Bedrooms (120 - 160 sq.ft)"',
      '"PM 2.5 Filter | Coanda Airflow | Power Chill Mode | 100% Copper Condenser"',
      '"Cooling Capacity:5000 Watts | Voltage:230V Single Phase | Noise Level:32 dB"',
      '"https://images.unsplash.com/photo-1621905251189-08b45d6a269e?q=80&w=800&auto=format&fit=crop"',
      '"1 Year Comprehensive + 10 Years Inverter Compressor"',
      '"Available for Immediate Showroom Order"',
      '"false"',
    ].join(','),
    [
      '"Samsung 8.0 kg Front Load Digital Inverter Washing Machine"',
      '"Samsung"',
      '"washing-machine"',
      '"WW80T Series"',
      '"SAMSUNG-WW80T-DEMO"',
      '"8.0 kg"',
      '"5"',
      '""',
      '""',
      '""',
      '""',
      '""',
      '"Front load automatic washer featuring Hygiene Steam cycle, high-spin motor, and Diamond Drum fabric care."',
      '"Samsung 8.0 kg front-load washer is equipped with Digital Inverter technology for silent, energy-efficient cycles."',
      '"Families of 4 to 6 members"',
      '"Hygiene Steam Sanitize | Digital Inverter Motor | Diamond Drum Fabric Guard | Quick Wash 15m"',
      '"Capacity:8.0 kg | Spin Speed:1400 RPM | Motor Type:Digital Inverter"',
      '"https://images.unsplash.com/photo-1582735689369-4fe89db7114c?q=80&w=800&auto=format&fit=crop"',
      '"2 Years Comprehensive + 20 Years Motor"',
      '"Available on Showroom Order"',
      '"false"',
    ].join(','),
    [
      '"1.5 Ton Rotary Compressor (R32 / R410A Compatible)"',
      '"Universal Spares"',
      '"ac-spares"',
      '"Rotary-15T Series"',
      '"SPARE-COMP-15T-DEMO"',
      '"1.5 Ton"',
      '""',
      '""',
      '"R-32 / R-410A"',
      '""',
      '""',
      '""',
      '"Replacement rotary compressor unit for 1.5 ton split air conditioners. High volumetric efficiency OEM specification."',
      '"High-pressure rotary compressor engineered for OEM replacement in split air conditioning outdoor units."',
      '"HVAC Technicians & AC Repair Workshops"',
      '"High Pressure Discharge | High Volumetric Efficiency | Vibration Dampening Mounts"',
      '"Displacement:14.2 cc | Motor:Single Phase 230V | Lubricant:POE Synthetic Oil"',
      '"https://images.unsplash.com/photo-1581092335397-9583fe92d232?q=80&w=800&auto=format&fit=crop"',
      '"1 Year Showroom Replacement Guarantee"',
      '"In Stock at Spares Counter"',
      '"false"',
    ].join(','),
  ];

  const csvContent = `${headers}\n${sampleRows.join('\n')}\n`;

  return new NextResponse(csvContent, {
    status: 200,
    headers: {
      'Content-Type': 'text/csv; charset=utf-8',
      'Content-Disposition': 'attachment; filename="vdr_catalogue_import_template.csv"',
    },
  });
}
